name: Trigger auto deployment for container-app-example

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-example-AutoDeployTrigger-60840e43-31b7-4e1f-a484-00cb55033218.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEXAMPLE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEXAMPLE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEXAMPLE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: acrexampleterraform.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPEXAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEXAMPLE_REGISTRY_PASSWORD }}
          containerAppName: container-app-example
          resourceGroup: terraform-azure-container-try
          imageToBuild: acrexampleterraform.azurecr.io/container-app-example:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


